dist: trusty
sudo: required
language: bash
before_install:
  - sudo ./install.sh
  - composer self-update
  - composer install
before_script:
script:
  - sudo ./ox.php site:create site.dev
  - sudo ./ox.php site:delete site.dev
