dist: trusty
sudo: required
language: bash
addons:
    hosts:
        - site.dev
before_install:
    - sudo ./install.sh
    - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    - php composer-setup.php
    - php -r "unlink('composer-setup.php');"
    - sudo mv composer.phar /usr/local/bin/composer
    - composer install
before_script:
    - chmod -R 777 $HOME
script:
    - sudo ./ox.php site:create site.dev
    - sudo ./ox.php site:delete site.dev --no-prompt
    - sudo ./ox.php site:create site.dev --package=default
    - sudo ./ox.php site:delete site.dev --no-prompt
    - sudo ./ox.php site:create site.dev --package=mysql
    - sudo ./ox.php site:delete site.dev --no-prompt
    - sudo ./ox.php site:create site.dev --package=grav
    - sudo ./ox.php site:delete site.dev --no-prompt
    - sudo ./ox.php site:create site.dev --package=wordpress
    - sudo ./ox.php site:delete site.dev --no-prompt
